blueprint:
  name: Inovelli Blue Series Notification (ZHA)
  description: >-
    A script that sends an LED bar notification to an Inovelli Blue Series device (VZM31-SN, VZM35-SN).
  domain: script
  input:
    notification_device:
      name: Device
      description: Device to send the notification to.
      selector:
        device:
          integration: zha
          manufacturer: Inovelli
    LEDEffectType:
      name: LED Effect Type
      description: "Animation pattern to use for the notification."
      selector:
        select:
          mode: "dropdown"
          multiple: false
          options:
            - label: "Off"
              value: 0
            - label: "Solid"
              value: 1
            - label: "Fast Blink"
              value: 2
            - label: "Slow Blink"
              value: 3
            - label: "Pulse"
              value: 4
            - label: "Chase"
              value: 5
            - label: "Open/Close"
              value: 6
            - label: "Small to Big"
              value: 7
            - label: "Clear"
              value: 255
    LEDEffectColor:
      name: LED Effect Color
      description: "0:-254: Hue based on Color Wheel, 255: White"
      selector:
        number:
          min: 0
          max: 255
    LEDEffectLevel:
      name: LED Effect Level
      description: "0-100% Brightness Level"
      selector:
        number:
          min: 0
          max: 100
    LEDEffectDuration:
      name: LED Effect Duration
      description: "1-60: Duration in seconds, 61-120: Duration in minutes (minus 60), 120-254: Duration in hours (minus 120), 255: Indefinite duration"
      selector:
        number:
          min: 0
          max: 255
variables:
  device_str: !input notification_device
  device_ieee: "{{ (device_attr((device_str), 'identifiers')|list).0.1 }}"
mode: single
sequence:
  - service: zha.issue_zigbee_cluster_command
    data:
      ieee: "{{ device_ieee }}"
      endpoint_id: 1
      cluster_id: 64561
      cluster_type: in
      command: 1
      command_type: server
      args:
        - "{{ LEDEffectType |int }}"
        - !input LEDEffectColor
        - !input LEDEffectLevel
        - !input LEDEffectDuration
      manufacturer: "4655"
